name: Restrict pull requests into live
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  restrict-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Restrict branches
        run: |
          if [ "${{ github.head_ref }}" != "main" ] && [ "${{ github.base_ref }}" == "live" ]; then
            echo "Merge requests to live branch are only allowed from main branch."
            exit 1
          fi
